<?php
define('DVWA_WEB_PAGE_TO_ROOT','../');
require_once DVWA_WEB_PAGE_TO_ROOT.'dvwa/includes/dvwaPage.inc.php';
dvwaPageStartup(array('authenticated')); dvwaDatabaseConnect(); dvwaSecurityEnsureSchema(); require_once __DIR__.'/_intel_common.php';
$items=[
 ['Input detection','SQLi / XSS / Command Injection detector helpers','كواشف حقن SQL/XSS/الأوامر',function(){return function_exists('dvwaSecurityContainsSqlInjection')&&function_exists('dvwaSecurityContainsXss')&&function_exists('dvwaSecurityContainsCommandInjection');},'10','DETECT','اكتشاف'],
 ['Output encoding','Central HTML output escape helper','أداة ترميز مركزية لمخرجات HTML',function(){return function_exists('dvwaSecurityEscape');},'10','PROTECT','حماية'],
 ['Telemetry minimization','Redaction before telemetry persistence','تنقيح البيانات قبل حفظ المراقبة',function(){return function_exists('dvwaSecurityRedact');},'10','PRIVACY','خصوصية'],
 ['Prepared telemetry','Prepared statement insertion path','مسار إدخال باستخدام استعلامات مجهزة',function(){return function_exists('dvwaSecurityEvent');},'15','TELEMETRY','مراقبة'],
 ['Session controls','Session start + regeneration helpers','أدوات بدء وتجديد الجلسات',function(){return function_exists('dvwa_start_session')&&function_exists('session_regenerate_id');},'15','IDENTITY','هوية'],
 ['CSRF controls','Existing token validation helpers','أدوات التحقق من رموز CSRF',function(){return function_exists('checkToken')&&function_exists('generateSessionToken');},'15','REQUEST','طلب'],
 ['Upload hardening','Hardened upload source path available','مسار رفع ملفات محصّن متاح',function(){return is_file('../vulnerabilities/upload/source/impossible.php');},'10','FILES','ملفات'],
 ['Security headers','Application shell emits hardening headers','هيكل التطبيق يرسل رؤوس حماية',function(){return is_file('../dvwa/includes/dvwaPage.inc.php');},'15','EDGE','واجهة']
];
$cards='';$active=0;foreach($items as $i){$ok=(bool)$i[3]();if($ok)$active++;$cards.='<article class="si-control-card '.($ok?'ok':'warn').'"><div class="control-orbit"></div><div class="control-core"><span>'.($ok?'✓':'!').'</span></div><div class="control-meta"><span>'.siE(siText($i[4].' PTS',$i[4].' نقطة')).'</span><b>'.siE(siText($i[5],$i[6])).'</b></div><span class="control-state">'.siE(siText($ok?'ACTIVE':'REVIEW',$ok?'نشط':'مراجعة')).'</span><h3>'.siE(siText($i[0],$i[0])).'</h3><p>'.siE(siText($i[1],$i[2])).'</p><div class="control-line"><i style="width:'.($ok?'100':'45').'%"></i></div></article>';}
$posture=round($active/count($items)*100);
$body=siShell('CONTROL LIBRARY / DEFENSE STACK','مكتبة الضوابط / طبقات الدفاع','Security Controls','الضوابط الأمنية','A live defense stack showing which controls are available and what they protect.','طبقات دفاع حية توضح الضوابط المتاحة وما الذي تحميه.','green');
$body.='<div class="control-overview"><div class="control-score"><div class="score-ring" style="--score:'.$posture.'"><span>'.$posture.'<small>/100</small></span></div><div><small>'.siE(siText('DEFENSE POSTURE','الوضع الدفاعي')).'</small><h2>'.siE(siText($posture>=90?'HARDENED':'REVIEW',$posture>=90?'محكم':'مراجعة')).'</h2><p>'.siE(siText($active.' of '.count($items).' controls currently available.','يتوفر حاليًا '.$active.' من أصل '.count($items).' ضوابط.')).'</p></div></div><div class="defense-pipeline"><div><i>01</i><b>'.siE(siText('DETECT','اكتشاف')).'</b></div><span>→</span><div><i>02</i><b>'.siE(siText('BLOCK','حظر')).'</b></div><span>→</span><div><i>03</i><b>'.siE(siText('RECORD','تسجيل')).'</b></div><span>→</span><div><i>04</i><b>'.siE(siText('VERIFY','تحقق')).'</b></div></div></div>';
$body.='<div class="si-control-grid">'.$cards.'</div><section class="si-panel controls-philosophy"><header><span>'.siE(siText('DEFENSE IN DEPTH / HUD MAP','خريطة الدفاع متعدد الطبقات')).'</span><b>'.siE(siText('ACTIVE ARCHITECTURE','المعمارية النشطة')).'</b></header><div class="defense-map"><div class="map-node node-a"><i></i><b>'.siE(siText('INPUT','المدخلات')).'</b><small>'.siE(siText('Untrusted data','بيانات غير موثوقة')).'</small></div><div class="map-beam beam-a"></div><div class="map-node node-b"><i></i><b>'.siE(siText('DETECT','اكتشاف')).'</b><small>'.siE(siText('Validation layer','طبقة التحقق')).'</small></div><div class="map-beam beam-b"></div><div class="map-node node-c"><i></i><b>'.siE(siText('CONTAIN','احتواء')).'</b><small>'.siE(siText('Security control','ضابط أمني')).'</small></div><div class="map-beam beam-c"></div><div class="map-node node-d"><i></i><b>'.siE(siText('TELEMETRY','المراقبة')).'</b><small>'.siE(siText('Safe evidence','دليل آمن')).'</small></div></div><div class="si-three"><div><strong>'.siE(siText('DETECT','اكتشاف')).'</strong><small>'.siE(siText('Recognize suspicious input before dangerous sinks.','اكتشاف المدخلات المشبوهة قبل وصولها إلى نقاط خطرة.')).'</small></div><div><strong>'.siE(siText('CONTAIN','احتواء')).'</strong><small>'.siE(siText('Block or constrain the request while preserving the lab flow.','حظر الطلب أو تقييده مع الحفاظ على عمل المختبر.')).'</small></div><div><strong>'.siE(siText('OBSERVE','مراقبة')).'</strong><small>'.siE(siText('Record high-level telemetry without retaining secrets.','تسجيل بيانات عامة دون حفظ الأسرار.')).'</small></div></div></section>';
siBase('Security Controls','الضوابط الأمنية',$body,'security_controls');
