<?php
$ROOT='../'; define('DVWA_WEB_PAGE_TO_ROOT',$ROOT);
require_once DVWA_WEB_PAGE_TO_ROOT.'dvwa/includes/dvwaPage.inc.php';
dvwaPageStartup(['authenticated']); dvwaDatabaseConnect(); dvwaSecurityEnsureSchema();
require_once __DIR__.'/_intel_common.php';

function sdV($sql){ return siV($sql); }
function sdQ($sql){ return siQ($sql); }
function sdLabel($v){
    $map=['SQL Injection'=>'حقن قواعد البيانات','SQL Injection (Blind)'=>'حقن قواعد البيانات الأعمى','Blind SQL Injection'=>'حقن قواعد البيانات الأعمى','Command Injection'=>'حقن الأوامر','Reflected XSS'=>'حقن النصوص المنعكس','Stored XSS'=>'حقن النصوص المخزن','XSS (DOM)'=>'حقن النصوص في واجهة الصفحة','DOM XSS'=>'حقن النصوص في واجهة الصفحة','File Upload'=>'رفع الملفات','Brute Force'=>'تخمين كلمات المرور','CSRF'=>'تزوير الطلبات','Weak Session IDs'=>'معرّفات الجلسات الضعيفة'];
    return dvwaIsArabic() && isset($map[$v]) ? $map[$v] : $v;
}
$total=sdV('SELECT COUNT(*) FROM security_events');
$blocked=sdV("SELECT COUNT(*) FROM security_events WHERE result='Blocked'");
$successful=sdV("SELECT COUNT(*) FROM security_events WHERE result='Successful'");
$last24=sdV("SELECT COUNT(*) FROM security_events WHERE event_time >= DATE_SUB(NOW(), INTERVAL 24 HOUR)");
$types=sdQ('SELECT attack_type, COUNT(*) c FROM security_events GROUP BY attack_type ORDER BY c DESC, attack_type ASC');
$events=sdQ('SELECT id,event_time,attack_type,target,source_ip,result,reason,request_method,request_path,input_preview,operator FROM security_events ORDER BY event_time DESC,id DESC LIMIT 120');
$ops=sdQ('SELECT id,event_time,operation_type,target,source_ip,result,details,operator FROM security_operations ORDER BY event_time DESC,id DESC LIMIT 40');
$opsTypes=sdQ("SELECT operation_type,COUNT(*) c FROM security_operations WHERE event_time >= DATE_SUB(NOW(), INTERVAL 24 HOUR) GROUP BY operation_type ORDER BY c DESC,operation_type ASC");
$ops24=array_sum(array_map(fn($r)=>(int)$r['c'],$opsTypes));
$maxType=1; foreach($types as $t){$maxType=max($maxType,(int)$t['c']);}
$blockedRate=$total?round($blocked/$total*100):0;
$filterType=trim((string)($_GET['type']??'')); $filterResult=trim((string)($_GET['result']??'')); $q=trim((string)($_GET['q']??''));
$filtered=[]; foreach($events as $e){if($filterType!==''&&$e['attack_type']!==$filterType)continue;if($filterResult!==''&&$e['result']!==$filterResult)continue;if($q!==''&&stripos($e['attack_type'].' '.$e['target'].' '.$e['source_ip'].' '.$e['reason'].' '.$e['input_preview'].' '.$e['request_path'].' '.$e['operator'],$q)===false)continue;$filtered[]=$e;}
if(isset($_GET['export'])&&$_GET['export']==='csv'){
    header('Content-Type:text/csv;charset=utf-8'); header('Content-Disposition:attachment; filename="securedvwa-security-log.csv"');
    $out=fopen('php://output','w'); fputcsv($out,['Time','Attack Type','Target','Request','Input Preview','Operator','Source IP','Result','Reason']);
    foreach($filtered as $e) fputcsv($out,[$e['event_time'],$e['attack_type'],$e['target'],($e['request_method']?:'').' '.($e['request_path']?:''),$e['input_preview']?:'',$e['operator']?:'',$e['source_ip']?:'N/A',$e['result'],$e['reason']?:'']);
    fclose($out); exit;
}
$online=dvwaSecurityEnsureSchema();
$severity=$successful>0?'danger':($total>0?'watch':'safe');
$body=siShell('CYBER DEFENSE / COMMAND CENTER','الدفاع السيبراني / مركز القيادة','Security Command Center','مركز القيادة الأمنية','A cinematic, evidence-based view of attacks, defenses, and normal application activity.','واجهة سينمائية مبنية على الأدلة لعرض الهجمات وفعالية الدفاع والتشغيل الطبيعي للتطبيق.',$severity==='danger'?'red':'cyan');
$body.='<section class="soc-kpi-grid">';
$kpis=[['ATTACKS','الهجمات المكتشفة',$total,'threat'],['BLOCKED','الهجمات المحجوبة',$blocked,'blocked'],['SUCCESSFUL','الهجمات الناجحة',$successful,'danger'],['NORMAL OPS','العمليات الطبيعية',$ops24,'normal']];
foreach($kpis as $k){$body.='<article class="soc-kpi '.$k[3].'"><span>'.siE(siText($k[0],$k[1])).'</span><strong>'.(int)$k[2].'</strong><small>'.siE(siText($k[3]==='normal'?'Separate functional telemetry':'Recorded laboratory telemetry',$k[3]==='normal'?'بيانات تشغيل وظيفي مستقلة':'بيانات مختبرية مسجلة')).'</small><i></i></article>';}
$body.='</section>';
$body.='<section class="soc-command-panel"><div class="soc-command-copy"><span class="si-kicker">'.siE(siText('DEFENSE STATE','حالة الدفاع')).'</span><h2>'.siE(siText($successful>0?'ATTENTION REQUIRED':'DEFENSE NOMINAL',$successful>0?'يتطلب الانتباه':'الدفاع مستقر')).'</h2><p>'.siE(siText($successful>0?'Successful results were recorded. Review the investigation trail and retest the associated control.':'Recorded attacks are contained; normal operations remain separate from security-event metrics.',$successful>0?'تم تسجيل نتائج ناجحة. راجع مسار التحقيق وأعد اختبار الضابط المرتبط.':'الهجمات المسجلة محجوبة، والعمليات الطبيعية منفصلة عن إحصاءات الأحداث الأمنية.')).'</p></div><div class="soc-defense-orb"><div><b>'.$blockedRate.'%</b><span>'.siE(siText('BLOCKED','محجوب')).'</span></div><i></i><i></i><i></i></div></section>';
$bars=''; foreach(array_slice($types,0,7) as $i=>$t){$pct=round((int)$t['c']/$maxType*100);$bars.='<a class="threat-bar" href="?type='.rawurlencode($t['attack_type']).'" style="--h:'.max(8,$pct).'%"><span>'.(int)$t['c'].'</span><i></i><b>'.siE(sdLabel($t['attack_type'])).'</b></a>';}
$body.='<section class="soc-grid"><article class="soc-panel attack-landscape">'.siHeader('THREAT LANDSCAPE','مشهد التهديدات','3D TELEMETRY','مراقبة ثلاثية الأبعاد').'<div class="threat-stage"><div class="threat-floor"></div><div class="threat-bars">'.($bars?:siEmpty('No attacks recorded yet.','لا توجد هجمات مسجلة حتى الآن.')).'</div></div><div class="visual-legend"><span><i></i>'.siE(siText('Column height represents observed attack volume.','ارتفاع العمود يمثل حجم الهجوم المرصود.')).'</span><span>'.siE(siText('Use a column to filter the log.','استخدم العمود لتصفية السجل.')).'</span></div></article>';
$dist=''; foreach(array_slice($types,0,8) as $i=>$t){$pct=$total?round((int)$t['c']/$total*100):0;$dist.='<div class="composition-row"><div><span>'.siE(sdLabel($t['attack_type'])).'</span><b>'.$pct.'%</b></div><i><em style="width:'.$pct.'%"></em></i></div>';}
$body.='<article class="soc-panel composition-panel">'.siHeader('ATTACK COMPOSITION','تركيب الهجمات','RECORDED SHARE','الحصة المسجلة').'<div class="composition-orbit"><div class="composition-core"><strong>'.$total.'</strong><span>'.siE(siText('EVENTS','حدث')).'</span></div></div><div class="composition-list">'.($dist?:siEmpty('No attack composition data yet.','لا توجد بيانات لتركيب الهجمات بعد.')).'</div></article></section>';
$recent=array_slice($events,0,7);$stream='';foreach($recent as $r){$c=$r['result']==='Blocked'?'blocked':'successful';$stream.='<a class="event-card '.$c.'" href="investigation.php?id='.(int)$r['id'].'"><span class="event-pulse"></span><div><strong>'.siE(sdLabel($r['attack_type'])).'</strong><small>'.siE($r['target']).'</small></div><span class="event-result">'.siE($r['result']==='Blocked'?siText('BLOCKED','محجوب'):siText('SUCCESSFUL','ناجح')).'</span><time>'.siE($r['event_time']).'</time></a>';}
$body.='<section class="soc-grid second"><article class="soc-panel event-panel">'.siHeader('RECENT SECURITY EVENTS','أحدث الأحداث الأمنية','LIVE STREAM','تدفق مباشر').'<div class="event-stream">'.($stream?:siEmpty('No security events have been recorded.','لم يتم تسجيل أحداث أمنية بعد.')).'</div></article>';
$opsStream='';foreach($ops as $r){$opsStream.='<article class="event-card normal"><span class="event-pulse"></span><div><strong>'.siE($r['operation_type']).'</strong><small>'.siE($r['target']).'</small>'.($r['details']?'<small>'.siE($r['details']).'</small>':'').'</div><span class="event-result">'.siE(siText('NORMAL','طبيعي')).'</span><time>'.siE($r['event_time']).'</time></article>';}
$normalRows='';foreach($ops as $r){
    $normalRows.='<tr><td>'.siE($r['event_time']).'</td><td><span class="normal-action">'.siE($r['operation_type']).'</span></td><td><span class="normal-target">'.siE($r['target']).'</span></td><td><code class="input-preview normal-input">'.siE($r['details']?:siText('No user input','لا يوجد إدخال من المستخدم')).'</code></td><td><span class="normal-ip">'.siE($r['source_ip']?:'N/A').'</span></td></tr>';
}
$body.='<article class="soc-panel normal-panel">'.siHeader('NORMAL OPERATIONS','العمليات الوظيفية الطبيعية','FUNCTIONAL TELEMETRY','بيانات تشغيل وظيفي').'<div class="ops-summary"><div><b>'.$ops24.'</b><span>'.siE(siText('24H OPERATIONS','عمليات 24 ساعة')).'</span></div><div><b>'.count($opsTypes).'</b><span>'.siE(siText('FUNCTION TYPES','أنواع الوظائف')).'</span></div><div><b>'.count($ops).'</b><span>'.siE(siText('LATEST RECORDS','أحدث السجلات')).'</span></div></div><div class="log-wrap normal-log"><table><thead><tr><th>'.siE(siText('TIME','الوقت')).'</th><th>'.siE(siText('ACTION','العملية')).'</th><th>'.siE(siText('WHERE','القسم')).'</th><th>'.siE(siText('USER INPUT','إدخال المستخدم')).'</th><th>'.siE(siText('SOURCE IP','عنوان IP المصدر')).'</th></tr></thead><tbody>'.($normalRows?:'<tr><td colspan="5"><div class="table-empty">'.siE(siText('No normal operations have been recorded yet.','لم يتم تسجيل عمليات وظيفية طبيعية بعد.')).'</div></td></tr>').'</tbody></table></div><footer>'.siE(siText('Only meaningful functional requests are counted; routine redirects and page reloads are not counted as separate operations.','يتم احتساب الطلبات الوظيفية الفعلية فقط؛ ولا تُحسب إعادة التوجيه وتحديث الصفحة كعمليات منفصلة.')).'</footer></article></section>';
$logRows='';foreach($filtered as $e){
    $preview=$e['input_preview']?:'—'; $path=$e['request_path']?:'—'; $method=$e['request_method']?:'—'; $operator=$e['operator']?:'—';
    $logRows.='<tr><td>'.siE($e['event_time']).'</td><td><b>'.siE(sdLabel($e['attack_type'])).'</b></td><td>'.siE($e['target']).'</td><td><span class="method-pill">'.siE($method).'</span> <span class="path-preview">'.siE($path).'</span></td><td><code class="input-preview" title="'.siE($preview).'">'.siE($preview).'</code></td><td>'.siE($operator).'</td><td>'.siE($e['source_ip']?:'N/A').'</td><td><span class="result-pill '.($e['result']==='Blocked'?'blocked':'successful').'">'.siE($e['result']==='Blocked'?siText('Blocked','محجوب'):siText('Successful','ناجح')).'</span></td><td>'.siE($e['reason']?:siText('No reason recorded','لم يسجل سبب')).'</td></tr>';
}
$typeOptions='<option value="">'.siE(siText('All attack types','كل أنواع الهجمات')).'</option>';foreach($types as $t){$sel=$filterType===$t['attack_type']?' selected':'';$typeOptions.='<option value="'.siE($t['attack_type']).'"'.$sel.'>'.siE(sdLabel($t['attack_type'])).'</option>';}
$body.='<section class="soc-panel log-panel">'.siHeader('SECURITY LOG','السجل الأمني',count($filtered).' / '.count($events).' '.siText('VISIBLE','ظاهر'),count($filtered).' / '.count($events).' الظاهر').'<form class="log-toolbar" method="get"><select name="type">'.$typeOptions.'</select><select name="result"><option value="">'.siE(siText('All results','كل النتائج')).'</option><option value="Blocked"'.($filterResult==='Blocked'?' selected':'').'>'.siE(siText('Blocked','محجوب')).'</option><option value="Successful"'.($filterResult==='Successful'?' selected':'').'>'.siE(siText('Successful','ناجح')).'</option></select><input name="q" value="'.siE($q).'" placeholder="'.siE(siText('Search the security log','ابحث في السجل الأمني')).'"><button type="submit">'.siE(siText('SEARCH','بحث')).'</button><a href="dashboard.php">'.siE(siText('CLEAR','مسح')).'</a><a href="?export=csv">'.siE(siText('EXPORT CSV','تصدير CSV')).'</a></form><div class="log-wrap"><table><thead><tr><th>'.siE(siText('TIME','الوقت')).'</th><th>'.siE(siText('ATTACK TYPE','نوع الهجوم')).'</th><th>'.siE(siText('TARGET','الهدف')).'</th><th>'.siE(siText('REQUEST','الطلب')).'</th><th>'.siE(siText('INPUT / COMMAND PREVIEW','معاينة الإدخال / الأمر')).'</th><th>'.siE(siText('OPERATOR','المشغل')).'</th><th>'.siE(siText('SOURCE IP','عنوان المصدر')).'</th><th>'.siE(siText('RESULT','النتيجة')).'</th><th>'.siE(siText('REASON','السبب')).'</th></tr></thead><tbody>'.($logRows?:'<tr><td colspan="9"><div class="table-empty">'.siE(siText('No matching security records.','لا توجد سجلات أمنية مطابقة.')).'</div></td></tr>').'</tbody></table></div><footer>'.siE(siText('Security telemetry excludes passwords, authentication tokens, complete session identifiers, and full attack payloads.','بيانات المراقبة لا تتضمن كلمات المرور أو رموز المصادقة أو معرفات الجلسات الكاملة أو حمولات الهجوم الكاملة.')).'</footer></section>';
$body.='<div class="soc-refresh"><span class="live-dot"></span><strong>'.siE(siText($online?'TELEMETRY ONLINE':'TELEMETRY OFFLINE',$online?'المراقبة متصلة':'المراقبة متوقفة')).'</strong><span>'.siE(siText('Refresh the page after running a new lab test.','حدّث الصفحة بعد تنفيذ اختبار مختبري جديد.')).'</span></div>';
siBase('Security Dashboard','لوحة المراقبة الأمنية',$body,'security_dashboard');
