<?php
$ROOT='../'; define('DVWA_WEB_PAGE_TO_ROOT',$ROOT);
require_once DVWA_WEB_PAGE_TO_ROOT.'dvwa/includes/dvwaPage.inc.php'; dvwaPageStartup(['authenticated']); dvwaDatabaseConnect();
$schemaReady=dvwaSecurityEnsureSchema(); require_once __DIR__.'/_intel_common.php';
$checks=[
 ['Database connection','اتصال قاعدة البيانات',fn()=>isset($GLOBALS['___mysqli_ston'])&&$GLOBALS['___mysqli_ston'] instanceof mysqli&&@mysqli_ping($GLOBALS['___mysqli_ston'])],
 ['Security events table','جدول الأحداث الأمنية',fn()=>siV("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='security_events'")===1],
 ['Normal operations table','جدول العمليات الطبيعية',fn()=>siV("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='security_operations'")===1],
 ['Security detectors','كواشف الحماية',fn()=>function_exists('dvwaSecurityContainsSqlInjection')&&function_exists('dvwaSecurityContainsXss')&&function_exists('dvwaSecurityContainsCommandInjection')],
 ['Output escaping','ترميز المخرجات',fn()=>function_exists('dvwaSecurityEscape')&&dvwaSecurityEscape('<script>')!=='<script>'],
 ['Security headers','رؤوس الاستجابة الأمنية',fn()=>($s=@file_get_contents(DVWA_WEB_PAGE_TO_ROOT.'dvwa/includes/dvwaPage.inc.php'))!==false&&strpos($s,'X-Content-Type-Options: nosniff')!==false&&strpos($s,'X-Frame-Options: SAMEORIGIN')!==false&&strpos($s,'Referrer-Policy: no-referrer')!==false],
 ['Telemetry helpers','أدوات التسجيل الأمني',fn()=>function_exists('dvwaSecurityEvent')&&function_exists('dvwaSecurityOperation')],
 ['Upload hardening','تحصين رفع الملفات',fn()=>is_file(DVWA_WEB_PAGE_TO_ROOT.'vulnerabilities/upload/source/impossible.php')&&is_file(DVWA_WEB_PAGE_TO_ROOT.'hackable/uploads/.htaccess')],
];
$okCount=0;$rows='';foreach($checks as $c){$ok=false;try{$ok=(bool)$c[2]();}catch(Throwable $e){}if($ok)$okCount++;$rows.='<article class="health-check '.($ok?'ok':'warn').'"><span>'.($ok?'✓':'!').'</span><div><strong>'.siE(siText($c[0],$c[1])).'</strong><small>'.siE(siText($ok?'Verified at page load':'Requires review',$ok?'تم التحقق عند فتح الصفحة':'تحتاج إلى مراجعة')).'</small></div><b>'.($ok?'PASS':'CHECK').'</b></article>';}
$score=round($okCount/count($checks)*100);$events=siV('SELECT COUNT(*) FROM security_events');$ops=siV('SELECT COUNT(*) FROM security_operations');$e24=siV("SELECT COUNT(*) FROM security_events WHERE event_time>=DATE_SUB(NOW(),INTERVAL 24 HOUR)");$o24=siV("SELECT COUNT(*) FROM security_operations WHERE event_time>=DATE_SUB(NOW(),INTERVAL 24 HOUR)");
$body=siShell('SECURITY INTELLIGENCE / RUNTIME HEALTH','استخبارات الأمن / صحة التشغيل','Security Health Center','مركز صحة الأمن','Live checks for database connectivity, telemetry, hardening, and runtime integrity.','فحوصات حية لاتصال قاعدة البيانات والمراقبة والتحصين وسلامة التشغيل.','green');
if(!$schemaReady)$body.='<section class="health-warning"><strong>'.siE(siText('Telemetry database is not ready','قاعدة بيانات المراقبة غير جاهزة')).'</strong><p>'.siE(siText('No new database is required. The security tables are created inside the existing DVWA database when the MySQL connection and permissions are correct.','لا تحتاج إلى قاعدة بيانات جديدة. يتم إنشاء جداول الأمن داخل قاعدة DVWA الحالية عند سلامة اتصال MySQL والصلاحيات اللازمة.')).'</p></section>';
$body.='<section class="health-overview"><div class="health-ring" style="--score:'.$score.'"><b>'.$score.'%</b><span>'.siE(siText('HEALTH','الصحة')).'</span></div><div class="health-copy"><span class="si-kicker">'.siE(siText('RUNTIME STATUS','حالة التشغيل')).'</span><h2>'.siE(siText($score===100?'SYSTEM NOMINAL':'REVIEW REQUIRED',$score===100?'النظام مستقر':'تحتاج إلى مراجعة')).'</h2><p>'.siE(siText($okCount.' of '.count($checks).' checks passed at page load.',$okCount.' من أصل '.count($checks).' فحوصات نجحت عند فتح الصفحة.')).'</p></div><div class="health-live"><span></span>'.siE(siText('LIVE CHECKS','فحوصات حية')).'</div></section>';
$body.='<section class="si-panel health-grid-panel">'.siHeader('RUNTIME HEALTH CHECKS','فحوصات صحة التشغيل',$okCount.'/'.count($checks).' PASS',$okCount.'/'.count($checks).' ناجحة').'<div class="health-checks">'.$rows.'</div></section>';
$body.='<section class="health-metrics"><div><span>'.siE(siText('SECURITY EVENTS','الأحداث الأمنية')).'</span><b>'.$events.'</b><small>'.siE(siText($e24.' in 24 hours',$e24.' خلال 24 ساعة')).'</small></div><div><span>'.siE(siText('NORMAL OPERATIONS','العمليات الطبيعية')).'</span><b>'.$ops.'</b><small>'.siE(siText($o24.' in 24 hours',$o24.' خلال 24 ساعة')).'</small></div><div><span>'.siE(siText('DATABASE','قاعدة البيانات')).'</span><b>'.($schemaReady?'OK':'CHECK').'</b><small>'.siE(siText('Existing DVWA database','قاعدة DVWA الحالية')).'</small></div></section>';
$body.='<section class="si-panel health-explanation">'.siHeader('READING THIS CENTER','كيف تقرأ هذا المركز','REAL CHECKS ONLY','فحوصات فعلية فقط').'<p>'.siE(siText('The score is descriptive, not a guarantee of security. Each item above is tied to a concrete runtime or source check; security attacks and normal application operations are never mixed.','الدرجة وصفية وليست ضمانًا للأمان. كل عنصر أعلاه مرتبط بفحص فعلي وقت التشغيل أو بفحص للمصدر، كما أن الهجمات والعمليات الطبيعية لا تختلط في القياسات.')).'</p></section>';
siBase('Security Health Center','مركز صحة الأمن',$body,'security_health');
