<?php
$ROOT='../'; define('DVWA_WEB_PAGE_TO_ROOT',$ROOT);
require_once DVWA_WEB_PAGE_TO_ROOT.'dvwa/includes/dvwaPage.inc.php'; dvwaPageStartup(['authenticated']); dvwaDatabaseConnect(); dvwaSecurityEnsureSchema(); require_once __DIR__.'/_intel_common.php';
$events=siQ("SELECT id,event_time,attack_type,target,result,request_method,request_path,input_preview,reason FROM security_events WHERE event_time>=DATE_SUB(NOW(),INTERVAL 30 MINUTE) ORDER BY id DESC LIMIT 30");
$ops=siQ("SELECT event_time,operation_type,target,source_ip,result,details FROM security_operations WHERE event_time>=DATE_SUB(NOW(),INTERVAL 30 MINUTE) ORDER BY id DESC LIMIT 20");
$blocked=count(array_filter($events,fn($e)=>$e['result']==='Blocked'));$danger=count($events)-$blocked;
$body=siShell('SOC / ALERT CENTER','مركز العمليات / التنبيهات','Alert Center','مركز التنبيهات','A calm, readable signal wall that separates security alerts from normal application activity.','لوحة إشارات هادئة وواضحة تفصل التنبيهات الأمنية عن نشاط التطبيق الطبيعي.',$danger?'red':'cyan');
$body.='<section class="alert-overview '.($danger?'has-danger':'all-clear').'"><div class="alert-radar"><i></i><b></b><span>'.siE(siText('LIVE','مباشر')).'</span></div><div><span class="si-kicker">'.siE(siText('ACTIVE WINDOW / 30 MIN','النافذة النشطة / 30 دقيقة')).'</span><h2>'.siE(siText($danger?'ATTENTION SIGNALS PRESENT':'MONITORING STANDBY',$danger?'توجد إشارات تحتاج انتباهًا':'المراقبة في وضع الاستعداد')).'</h2><p>'.siE(siText('Blocked events remain visible as evidence of defensive action, not as successful attacks.','تظل الأحداث المحجوبة ظاهرة كدليل على عمل الحماية وليست هجمات ناجحة.')).'</p></div><div class="alert-counts"><div><b>'.$danger.'</b><span>'.siE(siText('ATTENTION','انتباه')).'</span></div><div><b>'.$blocked.'</b><span>'.siE(siText('BLOCKED','محجوب')).'</span></div><div><b>'.count($events).'</b><span>'.siE(siText('SECURITY','أمني')).'</span></div><div><b>'.count($ops).'</b><span>'.siE(siText('NORMAL','طبيعي')).'</span></div></div></section>';
$eventHtml='';foreach($events as $e){$cl=$e['result']==='Blocked'?'blocked':'danger';$req=trim(($e['request_method']?:'—').' '.($e['request_path']?:''));$preview=$e['input_preview']?:($e['reason']?:'—');$eventHtml.='<a class="alert-card '.$cl.'" href="investigation.php?id='.(int)$e['id'].'"><i></i><div><strong>'.siE(siAttackLabel($e['attack_type'])).'</strong><small>'.siE($e['target']).' · '.siE($e['event_time']).'</small><code class="alert-telemetry-code">'.siE($req).'</code><code class="alert-telemetry-preview">'.siE($preview).'</code></div><b>'.siE($e['result']==='Blocked'?siText('BLOCKED','محجوب'):siText('SUCCESSFUL','ناجح')).'</b><span>↗</span></a>';}
$opHtml='';foreach($ops as $e){$opHtml.='<article class="alert-card normal"><i></i><div><strong>'.siE(siText('Normal functional operation','عملية وظيفية طبيعية')).'</strong><small>'.siE($e['target']).' · '.siE($e['event_time']).'</small><code class="alert-telemetry-code normal-code">'.siE(siText('USER INPUT','إدخال المستخدم')).': '.siE($e['details']?:siText('None','لا يوجد')).'</code><code class="alert-telemetry-preview normal-code">'.siE(siText('SOURCE IP','عنوان IP المصدر')).': '.siE($e['source_ip']?:'N/A').'</code></div><b>'.siE(siText('NORMAL','طبيعي')).'</b><span>•</span></article>';}
$body.='<div class="alert-grid"><section class="si-panel alert-panel">'.siHeader('SECURITY SIGNALS','الإشارات الأمنية',count($events).' EVENTS','حدث '.count($events)).'<div class="alert-list">'.($eventHtml?:siEmpty('No active security alerts.','لا توجد تنبيهات أمنية نشطة.')).'</div></section><section class="si-panel alert-panel">'.siHeader('NORMAL OPERATIONS','العمليات الطبيعية',count($ops).' EVENTS','حدث '.count($ops)).'<div class="alert-list">'.($opHtml?:siEmpty('No normal operations in this window.','لا توجد عمليات طبيعية في هذه النافذة.')).'</div></section></div>';
$body.='<section class="alert-legend"><span><i class="danger"></i>'.siE(siText('Attention / successful result','انتباه / نتيجة ناجحة')).'</span><span><i class="blocked"></i>'.siE(siText('Blocked / contained','محجوب / تمت السيطرة عليه')).'</span><span><i class="normal"></i>'.siE(siText('Normal functional operation','عملية وظيفية طبيعية')).'</span></section>';
siBase('Alert Center','مركز التنبيهات',$body,'security_alerts');
