<?php
$ROOT='../'; define('DVWA_WEB_PAGE_TO_ROOT','../');
require_once DVWA_WEB_PAGE_TO_ROOT.'dvwa/includes/dvwaPage.inc.php';
dvwaPageStartup(['authenticated']); dvwaDatabaseConnect(); dvwaSecurityEnsureSchema(); require_once __DIR__.'/_intel_common.php';

$total=siV('SELECT COUNT(*) FROM security_events');
$blocked=siV("SELECT COUNT(*) FROM security_events WHERE result='Blocked'");
$successful=siV("SELECT COUNT(*) FROM security_events WHERE result='Successful'");
$ops=siV('SELECT COUNT(*) FROM security_operations');
$ops24=siV("SELECT COUNT(*) FROM security_operations WHERE event_time>=DATE_SUB(NOW(),INTERVAL 24 HOUR)");
$events24=siV("SELECT COUNT(*) FROM security_events WHERE event_time>=DATE_SUB(NOW(),INTERVAL 24 HOUR)");
$types=siQ('SELECT attack_type,COUNT(*) c FROM security_events GROUP BY attack_type ORDER BY c DESC');
$areas=[];
$vectorMap=[
 ['sqli','SQL Injection','حقن قواعد البيانات'],
 ['sqli_blind','Blind SQL Injection','حقن قواعد البيانات الأعمى'],
 ['exec','Command Injection','حقن الأوامر'],
 ['xss_r','Reflected XSS','حقن النصوص المنعكس'],
 ['xss_d','DOM XSS','حقن النصوص في واجهة الصفحة'],
 ['xss_s','Stored XSS','حقن النصوص المخزن'],
 ['upload','File Upload','رفع الملفات']
];
foreach($vectorMap as $v){
  $slug=$v[0];
  $ev=siV("SELECT COUNT(*) FROM security_events WHERE target='vulnerabilities/".$slug."'");
  $bl=siV("SELECT COUNT(*) FROM security_events WHERE target='vulnerabilities/".$slug."' AND result='Blocked'");
  $op=siV("SELECT COUNT(*) FROM security_operations WHERE target='vulnerabilities/".$slug."'");
  $areas[]=['slug'=>$slug,'label'=>$v[1],'ar'=>$v[2],'c'=>$ev,'blocked'=>$bl,'ops'=>$op];
}
$recentEvents=siQ("SELECT event_time,attack_type,target,result,source_ip,request_method,request_path,input_preview,reason FROM security_events ORDER BY event_time DESC,id DESC LIMIT 5");
$recentOps=siQ("SELECT event_time,operation_type,target,source_ip,details FROM security_operations ORDER BY event_time DESC,id DESC LIMIT 5");
$hourThreat=[];$hourOps=[];
for($i=23;$i>=0;$i--){$h=date('Y-m-d H:00:00',strtotime('-'.$i.' hour'));$hourThreat[$h]=0;$hourOps[$h]=0;}
$q=siQ("SELECT DATE_FORMAT(event_time,'%Y-%m-%d %H:00:00') h,COUNT(*) c FROM security_events WHERE event_time>=DATE_SUB(NOW(),INTERVAL 24 HOUR) GROUP BY h");foreach($q as $r)if(isset($hourThreat[$r['h']]))$hourThreat[$r['h']]=(int)$r['c'];
$q=siQ("SELECT DATE_FORMAT(event_time,'%Y-%m-%d %H:00:00') h,COUNT(*) c FROM security_operations WHERE event_time>=DATE_SUB(NOW(),INTERVAL 24 HOUR) GROUP BY h");foreach($q as $r)if(isset($hourOps[$r['h']]))$hourOps[$r['h']]=(int)$r['c'];
$maxPulse=1;foreach($hourThreat as $h=>$v)$maxPulse=max($maxPulse,$v,$hourOps[$h]);
$sourceFiles=['vulnerabilities/sqli/source/low.php','vulnerabilities/sqli_blind/source/low.php','vulnerabilities/exec/source/low.php','vulnerabilities/xss_r/source/low.php','vulnerabilities/xss_s/source/low.php','vulnerabilities/xss_d/index.php','vulnerabilities/upload/source/low.php'];
$coverage=0;foreach($sourceFiles as $f)if(is_file(DVWA_WEB_PAGE_TO_ROOT.$f))$coverage++;
$defense=$total?round($blocked/$total*100):100;$score=round(($coverage/7*60)+($defense*0.4));
$labels=[];$values=[];foreach($types as $t){$labels[]=siAttackLabel($t['attack_type']);$values[]=(int)$t['c'];}
$areaLabels=[];$areaValues=[];$areaOps=[];$areaBlocked=[];foreach($areas as $a){$areaLabels[]=$a['label'];$areaValues[]=(int)$a['c'];$areaOps[]=(int)$a['ops'];$areaBlocked[]=(int)$a['blocked'];}
$pulseLabels=[];$pulseThreat=[];$pulseOps=[];foreach($hourThreat as $h=>$v){$pulseLabels[]=date('H:00',strtotime($h));$pulseThreat[]=$v;$pulseOps[]=$hourOps[$h];}

$body=siShell('SECURITY REPORT / COMMAND BRIEF','التقرير الأمني / موجز القيادة','Security Command Report','تقرير القيادة الأمنية','A cinematic, evidence-first view of security outcomes, normal activity, coverage, and the current defense posture.','واجهة سينمائية مبنية على الأدلة لعرض النتائج الأمنية والنشاط الطبيعي والتغطية ووضع الدفاع الحالي.','cyan');
$body.='<section class="report-sheet report-v3" data-report="1">';
$body.='<div class="report-commandline"><span>HN://SECUREDVWA</span><i></i><b>'.siE(siText('LOCAL LAB · EVIDENCE STREAM','مختبر محلي · تدفق الأدلة')).'</b><time>'.date('Y-m-d · H:i').'</time></div>';
$body.='<section class="report-hero-v3"><div class="report-hero-copy"><span class="report-overline">SECURITY INTELLIGENCE / 07</span><h2>'.siE(siText('MISSION REPORT','تقرير المهمة الأمنية')).'</h2><p>'.siE(siText('One screen to explain the lab: what happened, what was blocked, what users normally did, and which evidence paths are ready to demonstrate.','شاشة واحدة لشرح المختبر: ماذا حدث، ماذا تم حجبه، ماذا فعل المستخدمون بشكل طبيعي، وما هي مسارات الأدلة الجاهزة للعرض.')).'</p><div class="report-hero-actions"><button type="button" class="si-btn si-btn-primary" data-report-jump="telemetry">'.siE(siText('OPEN TELEMETRY','فتح المراقبة')).'</button><button type="button" class="si-btn" data-report-jump="evidence">'.siE(siText('TRACE EVIDENCE','تتبع الأدلة')).'</button><button type="button" class="si-btn" onclick="window.print()">'.siE(siText('PRINT BRIEF','طباعة التقرير')).'</button></div></div><div class="report-reactor" data-reactor="'.$score.'"><div class="reactor-rings"><i></i><i></i><i></i></div><div class="reactor-core"><small>READINESS</small><strong data-report-score="'.$score.'">'.$score.'</strong><em>/100</em></div><span class="reactor-label">LIVE</span></div></section>';
$body.='<section class="report-kpis report-kpis-v3"><div class="rk-security"><span>SECURITY EVENTS</span><b>'.$total.'</b><small>'.$events24.' · 24H</small></div><div class="rk-blocked"><span>BLOCKED</span><b>'.$blocked.'</b><small>'.($total?round($blocked/$total*100):100).'% PREVENTION</small></div><div class="rk-normal"><span>NORMAL OPS</span><b>'.$ops.'</b><small>'.$ops24.' · 24H</small></div><div class="rk-success"><span>SUCCESSFUL</span><b>'.$successful.'</b><small>'.siE(siText('OBSERVED OUTCOMES','نتائج مرصودة')).'</small></div></section>';

$body.='<section id="telemetry" class="report-stage telemetry-stage"><div class="stage-head"><div><span>'.siE(siText('01 · LIVE TELEMETRY','01 · المراقبة الحية')).'</span><h3>'.siE(siText('Operational Event Horizon','أفق الأحداث التشغيلية')).'</h3></div><small>'.siE(siText('Threat stream ≠ normal stream','تدفق التهديد ≠ التدفق الطبيعي')).'</small></div><div class="telemetry-console"><div class="pulse-axis"><span>THREAT</span><span>NORMAL</span></div><div class="pulse-rail" data-pulse data-max="'.$maxPulse.'">';
for($i=0;$i<24;$i++){ $hh=$pulseLabels[$i];$th=$pulseThreat[$i];$op=$pulseOps[$i];$thh=$maxPulse?round($th/$maxPulse*100):0;$oph=$maxPulse?round($op/$maxPulse*100):0;$body.='<button type="button" class="pulse-node" data-hour="'.siE($hh).'" data-threat="'.$th.'" data-ops="'.$op.'" aria-label="'.siE($hh).'" style="--th:'.$thh.'%;--op:'.$oph.'%"><span class="pulse-time">'.siE($hh).'</span><i class="pulse-threat"></i><i class="pulse-normal"></i></button>'; }
$body.='</div><div class="pulse-readout-v3" data-pulse-readout><b>'.siE(siText('SELECT A TIME WINDOW','اختر نافذة زمنية')).'</b><span>'.siE(siText('Click a node to compare security events and normal operations.','اضغط على نقطة لمقارنة الأحداث الأمنية بالعمليات الطبيعية.')).'</span></div></div></section>';

$body.='<section class="report-stage split-stage"><div class="stage-head"><div><span>'.siE(siText('02 · SIGNAL COMPOSITION','02 · تركيب الإشارات')).'</span><h3>'.siE(siText('Threat Signature','بصمة التهديد')).'</h3></div><small>'.count($values).' '.siE(siText('observed types','أنواع مرصودة')).'</small></div><div class="signal-layout"><div class="signal-orbit" data-donut><div class="signal-sweep"></div><div class="signal-core"><strong>'.$total.'</strong><span>'.siE(siText('EVENTS','أحداث')).'</span></div></div><div class="signal-list">';foreach($labels as $i=>$l){$pct=$total?round($values[$i]/$total*100):0;$body.='<button type="button" class="signal-row" data-legend-index="'.$i.'" data-value="'.$values[$i].'" data-label="'.siE($l).'" style="--share:'.$pct.'%"><i></i><span>'.$i+1 .'. '.siE($l).'</span><b>'.$values[$i].'</b><em>'.$pct.'%</em></button>';}$body.='</div></div></section>';

$body.='<section id="evidence" class="report-stage evidence-stage"><div class="stage-head"><div><span>'.siE(siText('03 · EVIDENCE CONSTELLATION','03 · كوكبة الأدلة')).'</span><h3>'.siE(siText('Seven Defense Vectors','محاور الدفاع السبعة')).'</h3></div><small>'.siE(siText('Click a vector','اضغط على أي محور')).'</small></div><div class="constellation"><div class="constellation-core"><span>HN</span><small>'.siE(siText('EVIDENCE','الأدلة')).'</small></div><div class="constellation-lines"></div><div class="constellation-nodes">';
for($i=0;$i<7;$i++){ $v=$areaValues[$i]??0;$opv=$areaOps[$i]??0;$blv=$areaBlocked[$i]??0;$label=$areaLabels[$i]??('Area '.($i+1));$pct=$total?round($v/$total*100):0;$angle=-90+$i*360/7;$body.='<button type="button" class="const-node" data-radar-index="'.$i.'" data-label="'.siE($label).'" data-value="'.$v.'" data-ops="'.$opv.'" data-blocked="'.$blv.'" style="--angle:'.$angle.'deg;--power:'.max(10,min(100,$pct)).'%"><span>'.($i+1).'</span><b>'.siE(siAttackLabel($label)).'</b><em>'.($v+$opv).'</em></button>';}
$body.='</div></div><div class="const-readout" data-radar-readout><b>'.siE(siText('SELECT A VECTOR','اختر محورًا')).'</b><span>'.siE(siText('The constellation maps observed evidence to the selected defense areas.','الكوكبة تربط الأدلة المرصودة بمحاور الدفاع المحددة.')).'</span></div></section>';

$body.='<section class="report-stage posture-stage"><div class="stage-head"><div><span>'.siE(siText('04 · DEFENSE POSTURE','04 · وضع الدفاع')).'</span><h3>'.siE(siText('Defense Reactor','مفاعل الدفاع')).'</h3></div><small>'.siE(siText('Outcome-only metric','مؤشر يعتمد على النتائج الأمنية فقط')).'</small></div><div class="posture-deck"><div class="posture-meter" data-posture="'.$defense.'"><svg viewBox="0 0 220 220" aria-hidden="true"><circle class="meter-track" cx="110" cy="110" r="88"></circle><circle class="meter-progress" cx="110" cy="110" r="88" pathLength="100"></circle></svg><div><strong>'.$defense.'%</strong><span>'.siE(siText('BLOCK RATE','نسبة الحجب')).'</span></div></div><div class="posture-copy"><span class="posture-state">'.siE(siText($defense>=90?'STABLE DEFENSE':'DEFENSE REVIEW',$defense>=90?'دفاع مستقر':'مراجعة الدفاع')).'</span><h4>'.siE(siText('Security outcomes remain isolated from routine application activity.','تبقى النتائج الأمنية معزولة عن نشاط التطبيق الاعتيادي.')).'</h4><p>'.siE(siText('Normal operations are counted separately so routine use does not inflate or dilute the security outcome.','يتم احتساب العمليات الطبيعية بشكل مستقل حتى لا يؤدي الاستخدام الاعتيادي إلى تضخيم أو تشويه النتيجة الأمنية.')).'</p><div class="posture-stats"><span><b>'.$blocked.'</b>'.siE(siText('blocked','محجوب')).'</span><span><b>'.$successful.'</b>'.siE(siText('successful','ناجح')).'</span><span><b>'.$ops24.'</b>'.siE(siText('normal / 24h','طبيعي / 24س')).'</span></div></div></div></section>';

$body.='<section class="report-stage ledger-stage"><div class="stage-head"><div><span>'.siE(siText('05 · EVIDENCE LEDGER','05 · سجل الأدلة')).'</span><h3>'.siE(siText('What the system actually observed','ما الذي رصده النظام فعليًا')).'</h3></div><small>'.siE(siText('Recent records','السجلات الأخيرة')).'</small></div><div class="ledger-grid"><div class="ledger-panel"><header><b>'.siE(siText('SECURITY','أمني')).'</b><span>'.count($recentEvents).'</span></header><div class="ledger-list">';
if($recentEvents){foreach($recentEvents as $r){$preview=trim((string)$r['input_preview']);$path=trim((string)$r['request_path']);$method=trim((string)$r['request_method']);$body.='<article class="ledger-item security"><time>'.siE($r['event_time']).'</time><div><strong>'.siE(siAttackLabel($r['attack_type'])).'</strong><span>'.siE($method.' '.($path?:$r['target'])).'</span><small>'.siE($preview?:($r['reason']?:'—')).'</small></div><b>'.siE(siResultLabel($r['result'])).'</b></article>';}}else{$body.=siEmpty('No security events recorded','لا توجد أحداث أمنية مسجلة');}$body.='</div></div><div class="ledger-panel"><header><b>'.siE(siText('NORMAL OPERATIONS','عمليات طبيعية')).'</b><span>'.count($recentOps).'</span></header><div class="ledger-list">';
if($recentOps){foreach($recentOps as $r){$body.='<article class="ledger-item normal"><time>'.siE($r['event_time']).'</time><div><strong>'.siE(siText('Normal operation','عملية طبيعية')).'</strong><span>'.siE($r['operation_type'].' · '.$r['target']).'</span><small>'.siE($r['details']?:'—').' · '.siE($r['source_ip']?:'—').'</small></div><b>NORMAL</b></article>';}}else{$body.=siEmpty('No normal operations recorded','لا توجد عمليات طبيعية مسجلة');}$body.='</div></div></div></section>';

$body.='<section class="report-stage coverage-stage"><div class="stage-head"><div><span>'.siE(siText('06 · RELEASE READINESS','06 · جاهزية الإصدار')).'</span><h3>'.siE(siText('Evidence Path','مسار الأدلة')).'</h3></div><small>'.$coverage.'/7</small></div><div class="readiness-track">';for($i=1;$i<=7;$i++){ $on=$i<=$coverage?'ready':'';$body.='<button type="button" class="readiness-node '.$on.'" data-coverage="'.$i.'"><i>'.sprintf('%02d',$i).'</i><span>'.siE(siText('VECTOR '.$i,'المحور '.$i)).'</span><b></b></button>';}$body.='</div><div class="readiness-readout" data-coverage-readout><b>'.siE(siText('Seven selected vulnerability areas','المناطق السبع المختارة')).'</b><span>'.siE(siText('Each vector is a presentation path for demonstrating the original behavior, the security outcome, and the evidence trail.','كل محور يمثل مسار عرض لإثبات السلوك الأصلي والنتيجة الأمنية ومسار الأدلة.')).'</span></div></section>';

$body.='<footer class="report-footer-v3"><span>HN://SECUREDVWA · LOCAL LAB</span><b>'.siE(siText('Evidence first · sensitive credentials excluded from telemetry','الأدلة أولًا · بيانات الاعتماد الحساسة مستبعدة من المراقبة')).'</b><time>'.date('Y-m-d H:i').'</time></footer></section>';
$body.='<script>window.HN_REPORT_DATA='.json_encode(['labels'=>$labels,'values'=>$values,'areaLabels'=>$areaLabels,'areaValues'=>$areaValues,'areaOps'=>$areaOps,'areaBlocked'=>$areaBlocked,'coverage'=>$coverage,'defense'=>$defense,'score'=>$score],JSON_UNESCAPED_UNICODE|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT).';</script><script src="../dvwa/js/hn_report.js"></script>';
siBase('Security Report','التقرير الأمني',$body,'security_report');
