<?php
$ROOT='../'; define('DVWA_WEB_PAGE_TO_ROOT','../');
require_once DVWA_WEB_PAGE_TO_ROOT.'dvwa/includes/dvwaPage.inc.php'; dvwaPageStartup(['authenticated']); dvwaDatabaseConnect(); dvwaSecurityEnsureSchema(); require_once __DIR__.'/_intel_common.php';
$known=[['SQL Injection',5,'حقن قواعد البيانات'],['Blind SQL Injection',5,'حقن قواعد البيانات الأعمى'],['Command Injection',5,'حقن الأوامر'],['Reflected XSS',4,'حقن النصوص المنعكس'],['DOM XSS',4,'حقن النصوص في واجهة الصفحة'],['Stored XSS',4,'حقن النصوص المخزن'],['File Upload',5,'رفع الملفات']];
$obs=siQ("SELECT attack_type,COUNT(*) c,SUM(CASE WHEN result='Successful' THEN 1 ELSE 0 END) s FROM security_events GROUP BY attack_type");$map=[];foreach($obs as $r)$map[$r['attack_type']]=[(int)$r['c'],(int)$r['s']];
$risk=[];$total=0;$success=0;foreach($known as $k){$freq=$map[$k[0]][0]??0;$succ=$map[$k[0]][1]??0;$total+=$freq;$success+=$succ;$likelihood=$freq?min(5,max(1,(int)ceil($freq/2))):1;$impact=$succ?5:$k[1];$score=$impact*$likelihood;$level=$score>=20?'critical':($score>=12?'high':($score>=6?'medium':'low'));$risk[]=['en'=>$k[0],'ar'=>$k[2],'freq'=>$freq,'succ'=>$succ,'score'=>$score,'impact'=>$impact,'likelihood'=>$likelihood,'level'=>$level];}
$list='';foreach($risk as $r){$list.='<article class="risk-card '.$r['level'].'"><div class="risk-grade">'.siE(siText(strtoupper($r['level']),match($r['level']){'critical'=>'حرج','high'=>'مرتفع','medium'=>'متوسط','low'=>'منخفض'})).'</div><div><h3>'.siE(siText($r['en'],$r['ar'])).'</h3><p>'.siE(siText('Observed '.$r['freq'].' · Successful '.$r['succ'].' · Impact '.$r['impact'].' · Likelihood '.$r['likelihood'],'مرصود '.$r['freq'].' · ناجح '.$r['succ'].' · تأثير '.$r['impact'].' · احتمالية '.$r['likelihood'])).'</p></div><b>'.$r['score'].'<small>/25</small></b></article>';}
$body=siShell('RISK ANALYTICS / LAB MODEL','تحليلات المخاطر / نموذج المختبر','Risk Matrix','مصفوفة المخاطر','A transparent 5×5 laboratory heuristic built from recorded frequency and baseline impact.','نموذج مختبري واضح 5×5 مبني على التكرار المسجل والتأثير الأساسي.','red');
$body.='<section class="risk-summary"><div><span>'.siE(siText('OBSERVED ATTACKS','الهجمات المرصودة')).'</span><b>'.$total.'</b></div><div><span>'.siE(siText('SUCCESSFUL','الناجحة')).'</span><b>'.$success.'</b></div><div><span>'.siE(siText('SUCCESS RATE','نسبة النجاح')).'</span><b>'.($total?round($success/$total*100):0).'%</b></div><div><span>'.siE(siText('MODELED AREAS','المناطق المقيمة')).'</span><b>'.count($risk).'</b></div></section>';
$matrix='';for($y=5;$y>=1;$y--){$matrix.='<div class="risk-row"><b>'.$y.'</b>';for($x=1;$x<=5;$x++){$v=$x*$y;$matrix.='<i class="r'.$v.'" title="'.siE(siText('Impact '.$y.' × Likelihood '.$x,'التأثير '.$y.' × الاحتمالية '.$x)).'">'.$v.'</i>';}$matrix.='</div>';}
$body.='<section class="risk-main"><div class="si-panel risk-grid-panel">'.siHeader('5 × 5 RISK GRID','شبكة المخاطر 5 × 5','IMPACT × LIKELIHOOD','التأثير × الاحتمالية').'<div class="risk-grid-wrap"><div class="risk-matrix">'.$matrix.'<footer><span>'.siE(siText('LOW','منخفض')).'</span><b>'.siE(siText('LIKELIHOOD','الاحتمالية')).'</b><span>'.siE(siText('HIGH','مرتفع')).'</span></footer></div><div class="risk-orb"><i></i><i></i><b>'.siE(siText('RISK','مخاطر')).'</b></div></div></div><div class="si-panel">'.siHeader('THREAT SURFACE','سطح التهديد','7 AREAS','7 مناطق').'<div class="risk-list">'.$list.'</div></div></section>';
$body.='<section class="si-panel risk-method">'.siHeader('MODEL TRANSPARENCY','شفافية النموذج','LAB HEURISTIC','مقياس مختبري').'<div class="model-steps"><div><b>01</b><strong>'.siE(siText('FREQUENCY','التكرار')).'</strong><small>'.siE(siText('Frequency contributes to likelihood from 1–5.','التكرار يساهم في تحديد الاحتمالية من 1 إلى 5.')).'</small></div><div><b>02</b><strong>'.siE(siText('IMPACT','التأثير')).'</strong><small>'.siE(siText('Each vulnerability has a baseline impact; successful paths raise it.','لكل ثغرة تأثير أساسي؛ والمسار الناجح يرفع التأثير.')).'</small></div><div><b>03</b><strong>'.siE(siText('SCORE','الدرجة')).'</strong><small>'.siE(siText('Score = impact × likelihood. This is not a CVSS score.','الدرجة = التأثير × الاحتمالية. وهذه ليست درجة CVSS.')).'</small></div></div></section>';
siBase('Risk Matrix','مصفوفة المخاطر',$body,'security_risk');
