<?php
$ROOT='../'; define('DVWA_WEB_PAGE_TO_ROOT','../');
require_once DVWA_WEB_PAGE_TO_ROOT.'dvwa/includes/dvwaPage.inc.php'; dvwaPageStartup(['authenticated']); dvwaDatabaseConnect(); dvwaSecurityEnsureSchema(); require_once __DIR__.'/_intel_common.php';
$rows=siQ("SELECT id,DATE_FORMAT(event_time,'%Y-%m-%d %H:%i:%s') t,attack_type,target,result FROM security_events ORDER BY event_time DESC,id DESC LIMIT 80");
$items='';foreach($rows as $r){$ok=$r['result']==='Blocked';$items.='<article class="timeline-item '.($ok?'blocked':'danger').'"><span class="timeline-dot"></span><time>'.siE($r['t']).'</time><div><strong>'.siE(siAttackLabel($r['attack_type'])).'</strong><small>'.siE($r['target']).'</small></div><b>'.siE($ok?siText('BLOCKED','محجوب'):siText('SUCCESSFUL','ناجح')).'</b></article>';}
$body=siShell('THREAT INTELLIGENCE / EVENT STREAM','استخبارات التهديدات / تدفق الأحداث','Threat Timeline','الخط الزمني للتهديدات','A chronological replay of recorded security telemetry, designed for clear demonstration and investigation.','إعادة عرض زمنية للبيانات الأمنية المسجلة، مصممة للعرض الواضح والتحقيق.','blue');
$body.='<section class="si-panel timeline-panel">'.siHeader('EVENT TIMELINE','الخط الزمني للأحداث',count($rows).' LOADED','تم تحميل '.count($rows)).'<div class="timeline-track">'.($items?:siEmpty('Telemetry is waiting for events.','المراقبة بانتظار أحداث جديدة.')).'</div></section>';
$body.='<section class="si-panel timeline-reading">'.siHeader('READ THE STREAM','قراءة التدفق','3 SIGNALS','3 إشارات').'<div class="signal-cards"><div><b>'.siE(siText('BLOCKED','محجوب')).'</b><small>'.siE(siText('A defensive control triggered.','تم تفعيل ضابط دفاعي.')).'</small></div><div><b>'.siE(siText('SUCCESSFUL','ناجح')).'</b><small>'.siE(siText('A lab path reached its target and requires review.','وصل مسار مختبري إلى الهدف ويحتاج مراجعة.')).'</small></div><div><b>'.siE(siText('TARGET','الهدف')).'</b><small>'.siE(siText('Only a high-level component is shown; secrets are omitted.','يظهر المكوّن العام فقط؛ ولا يتم عرض الأسرار.')).'</small></div></div></section>';
siBase('Threat Timeline','الخط الزمني للتهديدات',$body,'security_timeline');
